### ISSUE TITLE
Nice to meet you and here is the first feedback

### ISSUE THREAD

**Issue by luongvo** [anticafe/survey_app#20]
Hello Triet @anticafe, 

Nice to e-meet you 👋 and thanks for your effort on this submission. My name is Lucas - an Android Developer at Nimble and I would like to conduct the feedback via Issue tickets regarding your performance here. 

Keep in mind, this is a bidirectional process, so we would love to hear back from you as well, so please don’t hesitate to raise your question/correction in case we missed anything. 

If we’re aligned on any issue here and you’d like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up those fixes 😇

I hope you find the process enjoyable. Good luck and happy coding 🤘

**Here is our first feedback for the app:**
- List item reset after went back to home screen from the detail screen
- Scroll to the last page got `No result found` for the first time and `Unknown error` for next times (scroll back 1 item and next again)? They were not consistent and should be revised.
- Suppress the warning without proper configuration: android:allowBackup (https://medium.com/mindorks/auto-backup-in-android-dont-do-it-unless-you-know-it-cc9fe2f9176b)
- No proguard

**Comment by trietbui85** [comment]
Hello Lucas @luongvo, nice to meet you.

Thanks for your feedback. Here is my comment:
>List item reset after went back to home screen from the detail screen

I try to reproduce it by: load the first page, then scroll to end of the first page so that the second page to load more. After that, touch on "Take the survey" button to open the detail screen. Then press BACK key to back to home screen. However, I still see the list item there (with 2 pages data as well as previous indicator index). 
I think there should be a special step to reproduce that issue - could you please give me more detail?

**Comment by trietbui85** [comment]
And about **AllowBackup**
>Suppress the warning without proper configuration: android:allowBackup

You're right. I should disable `autoBackup` instead. Fixed in #25

**Comment by luongvo** [comment]
> List item reset after went back to home screen from the detail screen

![20200210_165614](https://user-images.githubusercontent.com/16315358/74140194-37b0f180-4c27-11ea-84b6-9128d6329f4e.gif)
@anticafe here it is, commit id 4c79d8fc64347199a6648c19d576425d2ab8b694

**Comment by trietbui85** [comment]
Well I see. According to @luongvo 's [comment](https://github.com/anticafe/survey_app/issues/24#issuecomment-584030125), you take the revision based on submission date, thus this issue still there. However, after that I make a commit 3fc0a93706 in PR #16 to fix it. So, this issue is now fixed.

**Comment by trietbui85** [comment]
Proguard rule is added via commit aec095d.

**Comment by trietbui85** [comment]
All issues has been fixed. Please help me to verify. Your comments are welcome 👍 .

**Comment by luongvo** [comment]
> Proguard rule is added via commit [aec095d](https://github.com/anticafe/survey_app/commit/aec095dc10fbd618382b1c457bbc9bf5fa53a5c3).

So, we have to apply proguard for debug build type too? That doesn't make sense tbh

**Comment by trietbui85** [comment]
@luongvo Proguard is only applied when `minifyEnabled true`. In my case, it is set to false for debug build instead, so I believe it doesn't take effect.
>https://github.com/anticafe/survey_app/blob/2707bcfa29258f8f1a5e38d0611a464260a7c0d9/app/build.gradle#L60

In Github, there are [many repositories](https://github.com/search?l=Kotlin&p=2&q=%22minifyEnabled+false%22&type=Code) has `minifyEnabled false` for debug build too. I guess they have the same reason as mine: they want to test proguard rule but doesn't have release configuration (keystore) available yet, thus use debug build temporarily.

**Comment by luongvo** [comment]
@anticafe but you're pointing to the same proguard config for both build type. Nvm, it doesn't effect at least. 👍
