### ISSUE TITLE
Things could be improve when using Navigation Component 

### ISSUE THREAD

**Issue by luongvo** [anticafe/survey_app#24]
- Use Navigation Component "safeArgs", you imported it but still using the traditional passing Bundle and null check type: https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/detail/DetailFragment.kt#L52 and here https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/main/MainFragment.kt#L108

**Comment by trietbui85** [comment]
Hi @luongvo Please check my latest code. I think this issue has been improved 2 days ago via commit 6d1ffa0b and 7f05ff6 in PR #18

**Comment by sleepylee** [comment]
hi @anticafe, I'm @luongvo's colleague, kindly notice that the assessment we took was based on the submission date, any progress comes after won't get counted at first, though, we always appreciate your effort on completing and improving the submission, we definitely take it into account but I just want to clarify on our assessment process. happy coding 💻

**Comment by trietbui85** [comment]
Hi @sleepylee and @luongvo 
It's fair to do code review base on the revision on submission date, although I don't know about that process before. However, it's good that you found something in my code needs to improve, like NavComponent SafeArgs 👍 . Now it was fixed via PR #18, so I will close this issue now.

**Comment by luongvo** [comment]
I found you used `RedundantOverride` to ignore unreachable code https://github.com/anticafe/survey_app/pull/18/files#diff-707b08b050921281054addbbfd660849R35? Any reason for this or just because of laziness 🤔

**Comment by trietbui85** [comment]
Nice catch 👍  @luongvo . Thanks for pointing it. That is my mistake when replacing the `BackPressedDispatcher` by NavComponent - the `onCreate` method useless and should be removed instead.
Fixed in 56f3219.
